import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { BsDiscord, BsGithub, BsTwitter } from "react-icons/bs";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tiago Silva - Portfólio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/icon.jpeg" />
      </Head>
      <main className="flex min-h-screen flex-row items-center justify-center bg-zinc-900 text-neutral-200">
        <div className="flex -translate-y-40 flex-col items-center justify-center">
          <Image
            className="m-2 rounded-full"
            src="/icon.jpeg"
            alt="Icon"
            width={225}
            height={225}
          />
          <div className="flex flex-col items-center justify-center">
            <div className="text-4xl font-bold">Tiago Silva</div>

            <div className="text-large m-1 text-center font-light">
              Full-stack Developer<br></br>Sines, Portugal
            </div>

            <div className="flex flex-row">
              <BsDiscord className="m-1 h-6 w-6 " />
              <BsGithub className="m-1 h-6 w-6" />
              <BsTwitter className="m-1 h-6 w-6 " />
            </div>

            <div className="mt-32 flex items-center justify-center  text-center text-2xl">
              Olá! Eu sou o Tiago Silva, tenho 16 anos vivo em Sines, Portugal
              <br></br> e sou desenvoledor Full-Stack.
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
